### PR TITLE
vscript fixes and additions

### LINKED ISSUE #166: [VSCRIPT] TraceLineComplex instance deallocation crash
### Steps to reproduce
1. Execute
```cpp
TraceLineComplex( Vector(), Vector(), null, 0, 0 ).Destroy()
```
2. Relaunch a map

### PR DESCRIPTION
**Pull request by samisalreadytaken**
Integer/float typemask is also the behaviour of VSquirrel.

This PR also fixes #166 along with unreported memory leaks of `FireBulletsInfo_t` and other vulnerable code.

https://github.com/mapbase-source/source-sdk-2013/pull/172/commits/4af6d0cdaafcd4d26623b15b8bab54d47f339dc0 removes unnecessary documentation text such as `CreateDamageInfo() : "Creates damage info"`. It should be used for useful information instead of repeating the function name.

https://github.com/mapbase-source/source-sdk-2013/pull/172/commits/5e444b2db919f30f9ed79c6789dcaffc438b849c removes the usermessage `CallClientScriptFunction` as its only use was to also send the entity itself; using entity messages is more appropriate for this situation. It also doesn't make much sense to implement player filtering as this input is fired to an entity, and it makes more sense that it is executed on every client that has received the entity.

This commit also kind of makes the `mapbase_usermessages.cpp` file redundant.

SquirrelSafeCheck should probably become a debug only check (with unit tests for each exit point) as what it checks for is static, and not possible to change in runtime.

---

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

File: sp/src/game/server/baseanimating.cpp [hunk 1]
```diff
@@ -305,7 +305,7 @@ BEGIN_ENT_SCRIPTDESC( CBaseAnimating, CBaseEntity, "Animating models" )
 	DEFINE_SCRIPTFUNC( GetNumBones, "Get the number of bones" )
 	DEFINE_SCRIPTFUNC( GetSequence, "Gets the current sequence" )
 	DEFINE_SCRIPTFUNC( SetSequence, "Sets the current sequence" )
-	DEFINE_SCRIPTFUNC( SequenceLoops, "Loops the current sequence" )
+	DEFINE_SCRIPTFUNC( SequenceLoops, "Does the current sequence loop?" )
```
Comment (Blixibon) [inline sp/src/game/server/baseanimating.cpp:308]: The clientside counterpart in `c_baseanimating.cpp` needs to be changed as well

**Review by Blixibon — COMMENTED** [review]
Would it be alright if I merged this now? I'm a few months late to this PR and I could see that you've continued to make changes in that time, so I want to make sure I'm not interrupting anything in progress. (not that you can't just open another PR)

**Comment by samisalreadytaken** [comment]
It's fine, I do not have anything planned.
