### PR TITLE
VScript serialisation rewrite

### LINKED ISSUE #99: [VSCRIPT] Save/Restore swaps around values of class instance members
### Describe the bug
When loading a saved game, the values of VScript class members will be swapped around.

### Steps to reproduce
1. Create a script that defines a custom class with several members
2. Have the script create an instance of the class
3. Save the game and load the save

### Expected behavior
Class instances should retain the values their members had when the game was saved

---

### Additional context
Example of class member values before loading save:
image

Example of class member values after loading save:
image

### LINKED ISSUE #120: [VSCRIPT] Static member serialisation crash
### Describe the bug
Object type is not recognised in `SquirrelVM::ReadObject`, triggering the `Error` in the default switch case.

Tested in the current `develop` branch before 7.0.

### Steps to reproduce
Save and load a class instance with static members:

```cs
class CTest
{
	static var = null
}

instance <- CTest()
```

### LINKED ISSUE #165: [VSCRIPT] Closure serialisation crash
### Describe the bug
Crash in serialisation of a closure that contains an instance from const table.

### Steps to reproduce
1. Place an instance in the const table. Instance type (native or not) does not matter.
```cs
class CTest{} getconsttable().INSTANCE <- CTest()
```
2. Make a closure that accesses a constant instance
```
function fn() { INSTANCE }
```
3. Save the game (and the closure)

### LINKED ISSUE #219: [VSCRIPT] Class instance serialisation error
### Describe the bug
Class instance member save/restore order is inconsistent. This issue is most apparent with an example.

### Steps to reproduce
Save the following class instance, observe the member ordering. Note that member names are numbers for clarity as the hashed order of strings is not obvious.
```cs
class CTest
{
	[6] = 600;
	[7] = 700;
	[8] = 800;
	[9] = 900;
	[10] = 1000;

	[1] = 100;
	[2] = 200;
	[3] = 300;
	[4] = 400;
	[5] = 500;
}

instance <- CTest()
```
Print using
```cs
foreach( k, v in instance.getclass() ) printl( k + " : " + instance[k] )
```
Before save, expected
```cs
1 : 100
2 : 200
3 : 300
4 : 400
5 : 500

6 : 600
7 : 700
8 : 800
9 : 900
10 : 1000
```
After load, values are incorrectly assigned
```cs
1 : 600
2 : 700
3 : 800
4 : 900
5 : 1000

6 : 100
7 : 200
8 : 300
9 : 400
10 : 500
```
This does not happen when class members are declared in (hash) order
```cs
class CTest
{
	[1] = 100;
	[2] = 200;
	[3] = 300;
	[4] = 400;
	[5] = 500;

	[6] = 600;
	[7] = 700;
	[8] = 800;
	[9] = 900;
	[10] = 1000;
}
```

---

### Additional context

The issue comes from `SquirrelVM` writing class members using hash iterator (`SQClass::Next`) while class instance loads members by iterating `SQClass::_defaultvalues` which is ordered by member declaration order.

### PR DESCRIPTION
**Pull request by samisalreadytaken**
Current implementation had too many problems and unfixable issues with the approach it took. I rewrote `SquirrelVM::WriteState()` and `SquirrelVM::ReadState()` from scratch, fixing not only the linked issues but also various other undocumented issues.

This PR fixes serialisation of attributes, threads and generators, improves performance by skipping the VM stack alltogether in serialisation - previously it would push and pop every object to the VM stack, unnecesarily adding a lot of overhead. A very rudimentary test showed this code is approximately 12% faster in `WriteState`, 30% faster in `ReadState`.

This obviously is not backwards compatible. The only way to keep it compatible would be keeping a copy of the old read code for matching version numbers.

---

#### Does this PR close any issues?
* fixes #120
* fixes #165
* fixes #219

fixes #99 (although this was already marked fixed, I believe this is the same issue as #219)

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

File: sp/src/vscript/vscript_squirrel.cpp [hunk 1]
```diff
@@ -22,13 +22,15 @@
 #include "sqstdmath.h"
 #include "sqstdstring.h"
 
-// HACK: Include internal parts of squirrel for serialization
```
Comment (reductor) [inline sp/src/vscript/vscript_squirrel.cpp:25]: This is still a HACK, in fact it's even a bigger reach into the internals now.

It would be good to look at what can be done to avoid over reaching too far into internals and abstract away what's needed, even if the parts that depend on internals are in their own cpp file.

It's worth also looking to push it up stream to the squirrel lang repo what ever is needed to have proper serialization, this initial version was very hacky and needed to reach into the internals, I did have plans to push more upstream.

Comment (samisalreadytaken) [reply sp/src/vscript/vscript_squirrel.cpp:25]: Implementing complete serialisation natively in Squirrel would be very a large change (and an undertaking), I don't see such feature being accepted any time soon if at all.

Having a substantial serialisation does require accessing the internals anyway. Adding interface to access what is required is also unrealistic since what is required is everything.

**Review by Blixibon — APPROVED** [review]
I've noticed this PR is no longer in a draft state, so I'm assuming you're done with these changes and you believe this is safe to be merged. I'm not familiar enough with most of the code involved to give a fair assessment on it, but I conducted a light review and I didn't see anything that stood out to me.

Due to the sensitivity of these changes, I'm going to wait before merging this to ensure there's no remaining objections or comments surrounding it.

**Comment by samisalreadytaken** [comment]
I think it's ready. I don't remember having any ref discrepancies left on save/restore.

Previous save-breaking changes doesn't seem to have increased saverestore version numbers, perhaps [`b2699f6`](https://github.com/mapbase-source/source-sdk-2013/pull/221/commits/b2699f63ca8619ee2f95e4674d110ae700c0d828) is not really needed.

**Review by Blixibon — APPROVED** [review]

**Comment by Blixibon** [comment]
I approved this again just to acknowledge that I reviewed the changes that were made since my previous approval.

Thank you so much for rewriting this implementation, and I'm sorry that it took me so long to merge it.
